fixes content offset issue
readium/r2-navigator-kotlin pull request #164
Opened 2020-09-25 11:20 UTC by aferditamuriqi

2020-10-08 09:34 UTC, mickael-menu commented on r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
> +                numPages = ceil((this.computeHorizontalScrollRange() / this.computeHorizontalScrollExtent()).toDouble()).roundToInt()
@aferditamuriqi Did you intend to round up the result? The problem is that dividing two `Int`s returns a floored `Int`, so you need to convert one of them to `Double` first.

```suggestion
                numPages = ceil(this.computeHorizontalScrollRange().toDouble() / this.computeHorizontalScrollExtent()).toInt()
```

2020-10-08 09:40 UTC, mickael-menu commented on r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
> +                numPages = ceil((this.computeHorizontalScrollRange() / this.computeHorizontalScrollExtent()).toDouble()).roundToInt()
Btw I just tried rounding up the result but the layout is worse, so I think the original code was correct.

2020-10-08 09:50 UTC, mickael-menu requested changes
@aferditamuriqi I think the changes related to `computeHoriziontalScrollExtent()` make sense. However I don't see much improvement for the offset issue. In some cases I felt that it was better, but when I compared the two branches on the same page it looks the same:

![Screenshot_20201008-113759](https://user-images.githubusercontent.com/58686775/95442845-2b1e9d80-095c-11eb-862f-2b73f500e81d.png)
![Screenshot_20201008-113652](https://user-images.githubusercontent.com/58686775/95442858-2e198e00-095c-11eb-84d6-150b8a3eb6df.png)

Do you have a book + location I can test to see if there's any improvement? Also can you check from the branch in R2 Reader directly? Maybe there's a part of the fix that is missing in the PR.

I'm testing on a Pixel 3a.

2020-10-08 20:01 UTC, aferditamuriqi commented on r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
> +                numPages = ceil((this.computeHorizontalScrollRange() / this.computeHorizontalScrollExtent()).toDouble()).roundToInt()
actually no it is correct, this is what i have in all my apps running,

2020-10-08 20:02 UTC, aferditamuriqi commented on r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
> +                numPages = ceil((this.computeHorizontalScrollRange() / this.computeHorizontalScrollExtent()).toDouble()).roundToInt()
did you test if with your suggestion? since that won't work i agree

2020-10-08 20:05 UTC, aferditamuriqi commented
> @aferditamuriqi I think the changes related to `computeHoriziontalScrollExtent()` make sense. However I don't see much improvement for the offset issue. In some cases I felt that it was better, but when I compared the two branches on the same page it looks the same.
> 
> Do you have a book + location + steps (swipes vs taps) I can test to see if there's any improvement? Also can you check from the branch in R2 Reader directly? Maybe there's a part of the fix that is missing in the PR.
> 
> I'm testing on a Pixel 3a.
> 
no there is nothing missing and you can reproduce this with any book, just don't use your suggested version, but the code that i pushed

2020-10-08 20:25 UTC, aferditamuriqi commented
before the fix in this PR, this is how some larger books while swiping could end up. 
after the fix in this PR, they are perfectly aligned. i can see if i can find the book, but these are QA screenshots. 

![1a657add-c326-4275-abf7-43bc5e9eb8fb](https://user-images.githubusercontent.com/17150623/95509619-bc086f80-0982-11eb-8988-65db878eb808.png)
![21de432d-91f2-4729-b0ef-5ec7b49e1a74](https://user-images.githubusercontent.com/17150623/95509627-bca10600-0982-11eb-9914-6b63be073f21.png)

2020-10-09 06:40 UTC, mickael-menu commented
I believe you that it fixes the issue in some cases, I think this problem is multifaceted. I took the screenshots from R2 Reader `develop` + your branch, by swiping to the end of a long chapter. As soon as you tap on the edge to turn pages it realigns the offset, so it's only related to swiping in this particular case.

So I'm fine merging this PR once we address the pending comment, but will keep https://github.com/readium/r2-navigator-kotlin/issues/146 opened.

> you can reproduce this with any book, just don't use your suggested version, but the code that i pushed

I tested with your code of course, I tried the `ceil` fix after the review.

2020-10-09 07:04 UTC, mickael-menu commented on r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
> +                numPages = ceil((this.computeHorizontalScrollRange() / this.computeHorizontalScrollExtent()).toDouble()).roundToInt()
But this line doesn't change anything compared to the original.

* [`computeHorizontalScrollRange()` and `computeHorizontalScrollExtent()`](https://developer.android.com/reference/androidx/core/view/ScrollingView#computeHorizontalScrollRange()) are both returning `Int`
* [dividing two `Int` returns `Int`](https://stackoverflow.com/questions/54106333/how-to-div-of-two-integer-into-decimal-in-kotlin) and is basically like a `floor()`
* from there, `ceil` and `roundToInt` do nothing since the fractional part is 0


<img width="943" alt="Screenshot 2020-10-09 at 08 57 26" src="https://user-images.githubusercontent.com/58686775/95552709-76dd4f80-0a0d-11eb-8d1e-5a81a61eab54.png">

2020-10-27 12:53 UTC, mickael-menu approved these changes
@aferditamuriqi I reverted the `ceil()` statement but I'm merging the rest. Feel free to open another PR if you have a related fix.

2020-10-27 12:54 UTC, merged